trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureCLI@2
  inputs:
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      docker build -t mylabacr4657.azurecr.io/web-game:tag 2048-game
      az acr login -n mylabacr4657
      docker push mylabacr4657.azurecr.io/web-game:tag

